# Menus
menu:
  Home: .
  Arquivo: archives
  Website W16: http://w16.com.br

# Customize
customize:
    logo:
        enabled: true
        width: 58
        height: 44
        url: images/icone-w16.png
    profile:
        enabled: true # Whether to show profile bar
        avatar: css/images/logo-w16.png
        gravatar: # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
        author: W16
        author_title: Desenvolvimento Web & Analytics
        location: Florianópolis, SC, Brasil
        follow: http://facebook.com/w16.web
    highlight: monokai
    sidebar: right # sidebar position, options: left, right
    thumbnail: true # enable posts thumbnail, options: true, false
    favicon: # path to favicon
    social_links:
        github: http://github.com/w16
        facebook: http://facebook.com/w16.web
        instagram: http://instagram.com/w16.web
        linkedin: https://www.linkedin.com/company/w16-otimiza%C3%A7%C3%A3o-de-performance-web

# Widgets
widgets:
    - recent_posts
    - category
    - archive
    - tag
    - tagcloud
    - links

# Search
search:
    swiftype: # enter swiftype install key here
    baidu: false # you need to disable other search engines to use Baidu search, options: true, false

# Comment
comment:
    disqus: w16blog # enter disqus shortname here
    duoshuo: # enter duoshuo shortname here
    youyan: # enter youyan uid here

# Share
share: default # options: jiathis, bdshare, addtoany, default

# Plugins
plugins:
    fancybox: true # options: true, false
    google_analytics: UA-41025917-2 # enter the tracking ID for your Google Analytics
    google_site_verification: # enter Google site verification code
    baidu_analytics: # enter Baidu Analytics hash key

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
    links:
        Hexo: http://hexo.io
